# sqlite: &sqlite
#   adapter: sqlite3
#   verbosity: quiet

# postgresql: &postgresql
#   adapter: postgresql
#   encoding: utf8
#   pool: 5
#   username: angular
#   password: password

# test:
#   <<: *sqlite
#   database: tmp/dbs/angular_devise_test.db

# development:
#   <<: *sqlite
#   database: tmp/dbs/angular_devise_development.db

# production:
#   <<: *postgresql
#   database: angular_devise_production


development: &DB
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: postgres
  password: 123
  min_messages: warning
  database: angular_devise_dev